# Generated by Django 3.2.6 on 2022-02-08 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220129_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='units',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0, 'Der Wert muss höher als null sein.')]),
        ),
        migrations.AlterField(
            model_name='bbr',
            name='position',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bbr',
            name='status',
            field=models.CharField(choices=[('FUX', 'Fux'), ('BURSCH', 'Bursch'), ('AH', 'Alter Herr'), ('', '')], max_length=30, null=True),
        ),
    ]
